//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minsur.OrdenServicio.Common.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constantes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constantes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minsur.OrdenServicio.Common.Recursos.Constantes", typeof(Constantes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a APROBADO.
        /// </summary>
        public static string Aprobado {
            get {
                return ResourceManager.GetString("Aprobado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2.
        /// </summary>
        public static string IdAplicacionOrdenServicio {
            get {
                return ResourceManager.GetString("IdAplicacionOrdenServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO RECOMIENDA.
        /// </summary>
        public static string NoRecomienda {
            get {
                return ResourceManager.GetString("NoRecomienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO VALIDADO.
        /// </summary>
        public static string NoValidado {
            get {
                return ResourceManager.GetString("NoValidado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RECHAZADO.
        /// </summary>
        public static string Rechazado {
            get {
                return ResourceManager.GetString("Rechazado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RECOMIENDA.
        /// </summary>
        public static string Recomienda {
            get {
                return ResourceManager.GetString("Recomienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjunto.
        /// </summary>
        public static string Ruta_Adjunto {
            get {
                return ResourceManager.GetString("Ruta_Adjunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a :: SELECCIONE ::.
        /// </summary>
        public static string Seleccione {
            get {
                return ResourceManager.GetString("Seleccione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ::TODOS::.
        /// </summary>
        public static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VALIDADO.
        /// </summary>
        public static string Validado {
            get {
                return ResourceManager.GetString("Validado", resourceCulture);
            }
        }
    }
}
