//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minsur.OrdenServicio.Common.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DictionaryErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DictionaryErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minsur.OrdenServicio.Common.Recursos.DictionaryErrors", typeof(DictionaryErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación realizada correctamente..
        /// </summary>
        public static string SOL00000 {
            get {
                return ResourceManager.GetString("SOL00000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese Usuario y Contraseña..
        /// </summary>
        public static string SOL00001 {
            get {
                return ResourceManager.GetString("SOL00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario y/o contraseña incorrecta..
        /// </summary>
        public static string SOL00002 {
            get {
                return ResourceManager.GetString("SOL00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo puede asignar gobernanzas en orden consecutivo.
        /// </summary>
        public static string SOL00003 {
            get {
                return ResourceManager.GetString("SOL00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La opción visualizar otros solo está disponible para los proyectos asignados.
        /// </summary>
        public static string SOL00004 {
            get {
                return ResourceManager.GetString("SOL00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un usuario no puede ser encargado de control de proyectos y encargado de procura y contrato al mismo tiempo..
        /// </summary>
        public static string SOL00005 {
            get {
                return ResourceManager.GetString("SOL00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ingresado ya existe.
        /// </summary>
        public static string SOL00006 {
            get {
                return ResourceManager.GetString("SOL00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al realizar la operación..
        /// </summary>
        public static string SOL99999 {
            get {
                return ResourceManager.GetString("SOL99999", resourceCulture);
            }
        }
    }
}
