//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minsur.OrdenServicio.Common.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SolicitudExport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SolicitudExport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minsur.OrdenServicio.Common.Recursos.SolicitudExport", typeof(SolicitudExport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÁREA FUNCIONAL.
        /// </summary>
        public static string AreaFuncional {
            get {
                return ResourceManager.GetString("AreaFuncional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORÍA.
        /// </summary>
        public static string Categoria {
            get {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPAÑÍA.
        /// </summary>
        public static string Compania {
            get {
                return ResourceManager.GetString("Compania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DENOMINACIÓN SERVICIO.
        /// </summary>
        public static string DenominacionServicio {
            get {
                return ResourceManager.GetString("DenominacionServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DENOMINACIÓN SOCIAL.
        /// </summary>
        public static string DenominacionSocial {
            get {
                return ResourceManager.GetString("DenominacionSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DÍAS CALENDARIO.
        /// </summary>
        public static string DiasCalendario {
            get {
                return ResourceManager.GetString("DiasCalendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTADO AUTORIZACIÓN ÁREA FUNCIONAL.
        /// </summary>
        public static string EstadoAutorizacionAreaFuncional {
            get {
                return ResourceManager.GetString("EstadoAutorizacionAreaFuncional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTADO AUTORIZACIÓN GERENTE CORPORATIVO.
        /// </summary>
        public static string EstadoAutorizacionGerenteCorporativo {
            get {
                return ResourceManager.GetString("EstadoAutorizacionGerenteCorporativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTADO AUTORIZACIÓN GERENTE PROYECTO.
        /// </summary>
        public static string EstadoAutorizacionGerenteProyecto {
            get {
                return ResourceManager.GetString("EstadoAutorizacionGerenteProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTADO RECOMENDACIÓN.
        /// </summary>
        public static string EstadoRecomendacion {
            get {
                return ResourceManager.GetString("EstadoRecomendacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTADO SOLICITUD.
        /// </summary>
        public static string EstadoSolicitud {
            get {
                return ResourceManager.GetString("EstadoSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTADO VALIDACIÓN.
        /// </summary>
        public static string EstadoValidacion {
            get {
                return ResourceManager.GetString("EstadoValidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FASE PROYECTO.
        /// </summary>
        public static string FaseProyecto {
            get {
                return ResourceManager.GetString("FaseProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FECHA AUTORIZACIÓN ÁREA FUNCIONAL.
        /// </summary>
        public static string FechaAutorizacionAreaFuncional {
            get {
                return ResourceManager.GetString("FechaAutorizacionAreaFuncional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FECHA AUTORIZACIÓN GERENTE CORPORATIVO.
        /// </summary>
        public static string FechaAutorizacionGerenteCorporativo {
            get {
                return ResourceManager.GetString("FechaAutorizacionGerenteCorporativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FECHA AUTORIZACIÓN GERENTE PROYECTO.
        /// </summary>
        public static string FechaAutorizacionGerenteProyecto {
            get {
                return ResourceManager.GetString("FechaAutorizacionGerenteProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FECHA INICIO.
        /// </summary>
        public static string FechaInicio {
            get {
                return ResourceManager.GetString("FechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FECHA RECOMENDACIÓN.
        /// </summary>
        public static string FechaRecomendacion {
            get {
                return ResourceManager.GetString("FechaRecomendacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FECHA SOLICITUD.
        /// </summary>
        public static string FechaSolicitud {
            get {
                return ResourceManager.GetString("FechaSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FECHA TÉRMINO.
        /// </summary>
        public static string FechaTermino {
            get {
                return ResourceManager.GetString("FechaTermino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FECHA VALIDACIÓN.
        /// </summary>
        public static string FechaValidacion {
            get {
                return ResourceManager.GetString("FechaValidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUENTE CONTRATO.
        /// </summary>
        public static string FuenteContrato {
            get {
                return ResourceManager.GetString("FuenteContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAFO.
        /// </summary>
        public static string Grafo {
            get {
                return ResourceManager.GetString("Grafo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONEDA.
        /// </summary>
        public static string Moneda {
            get {
                return ResourceManager.GetString("Moneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONTO ESTIMADO.
        /// </summary>
        public static string MontoEstimado {
            get {
                return ResourceManager.GetString("MontoEstimado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NÚMERO SOLICITUD.
        /// </summary>
        public static string NumeroSolicitud {
            get {
                return ResourceManager.GetString("NumeroSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROYECTO.
        /// </summary>
        public static string Proyecto {
            get {
                return ResourceManager.GetString("Proyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUC.
        /// </summary>
        public static string Ruc {
            get {
                return ResourceManager.GetString("Ruc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOLICITANTE.
        /// </summary>
        public static string Solicitante {
            get {
                return ResourceManager.GetString("Solicitante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIPO SOLICITUD.
        /// </summary>
        public static string TipoSolicitud {
            get {
                return ResourceManager.GetString("TipoSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UBICACIÓN SERVICIO.
        /// </summary>
        public static string UbicacionServicio {
            get {
                return ResourceManager.GetString("UbicacionServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USUARIO AUTORIZACIÓN ÁREA FUNCIONAL.
        /// </summary>
        public static string UsuarioAutorizacionAreaFuncional {
            get {
                return ResourceManager.GetString("UsuarioAutorizacionAreaFuncional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USUARIO AUTORIZACIÓN GERENTE CORPORATIVO.
        /// </summary>
        public static string UsuarioAutorizacionGerenteCorporativo {
            get {
                return ResourceManager.GetString("UsuarioAutorizacionGerenteCorporativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USUARIO AUTORIZACIÓN GERENTE PROYECTO.
        /// </summary>
        public static string UsuarioAutorizacionGerenteProyecto {
            get {
                return ResourceManager.GetString("UsuarioAutorizacionGerenteProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USUARIO RECOMENDACIÓN.
        /// </summary>
        public static string UsuarioRecomendacion {
            get {
                return ResourceManager.GetString("UsuarioRecomendacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USUARIO VALIDACIÓN.
        /// </summary>
        public static string UsuarioValidacion {
            get {
                return ResourceManager.GetString("UsuarioValidacion", resourceCulture);
            }
        }
    }
}
